[general]
import = [
    "~/.config/alacritty/themes/themes/one_light.toml"
]


[env]
TERM = "xterm-256color"

[font]
size = 17
[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"


[window]
# decorations = "none"
opacity = 0.8

[window.dimensions]
columns = 100
lines = 30

[keyboard] 
bindings = [ 
  {  key = "Return", mods = "Shift", chars = "\n" },
  { key = "Back", mods = "Control", chars = "\u001b\u007f" },
]

