import = [
    "~/.config/alacritty/themes/themes/hyper.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 13

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"


[window]
decorations = "none"
opacity = 1.0

[window.dimensions]
columns = 100
lines = 30
