#!/usr/bin/env sh
config=/home/murat/.config/alacritty/alacritty.yml
OPAQUE='opacity: 1.0'
TRANSPARENT='opacity: 0.8'

if grep -q "$OPAQUE" $config; then
  sed -i "s/$OPAQUE/$TRANSPARENT/g" $config
else
  sed -i "s/$TRANSPARENT/$OPAQUE/g" $config
fi