#!/usr/bin/env sh
set -euo

if test "$(gsettings get org.gnome.desktop.interface color-scheme)" = "'prefer-light'"; then
  gsettings set org.gnome.desktop.interface color-scheme prefer-dark
  gsettings set org.gnome.desktop.interface gtk-theme 'Yaru-blue-dark'
  sed -i 's/colors: \*one_light/colors: \*tokyonight/g' ~/.config/alacritty/alacritty.yml
  tmux set-option -g status-style fg=white,bg=black
else
  gsettings set org.gnome.desktop.interface color-scheme prefer-light
  gsettings set org.gnome.desktop.interface gtk-theme 'Yaru-blue'
  sed -i 's/colors: \*tokyonight/colors: \*one_light/g' ~/.config/alacritty/alacritty.yml
  tmux set-option -g status-style bg=white,fg=black
fi
