#!/usr/bin/env sh
set -euo
ALACRITTY_DARK='hyper'
ALACRITTY_LIGHT='atom_one_light'

if test "$(gsettings get org.gnome.desktop.interface color-scheme)" = "'prefer-light'"; then
  gsettings set org.gnome.desktop.interface color-scheme prefer-dark
  gsettings set org.gnome.desktop.interface gtk-theme 'Yaru-blue-dark'
  sed -i "s/$ALACRITTY_LIGHT/$ALACRITTY_DARK/g" ~/.config/alacritty/alacritty.toml
else
  gsettings set org.gnome.desktop.interface color-scheme prefer-light
  gsettings set org.gnome.desktop.interface gtk-theme 'Yaru-blue'
  sed -i "s/$ALACRITTY_DARK/$ALACRITTY_LIGHT/g" ~/.config/alacritty/alacritty.toml
fi
